version: "3"
w
services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: program
            POSTGRES_PASSWORD: program_password
        volumes:
            - postgresql:/var/lib/postgresql
            - ./postgres:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        networks:
            - internal

    gateway:
        build:
            dockerfile: Dockerfile.gateway
        container_name: gateway
        restart: always
        environment:
            SERVICE_HOST: gateway
            SERVICE_PORT: 8080

            FLIGHT_SERVICE_HOST: flight_service
            FLIGHT_SERVICE_PORT: 8060

            TICKET_SERVICE_HOST: ticket_serivce
            TICKET_SERVICE_PORT: 8070

            BONUS_SERVICE_HOST: bonus_service
            BONUS_SERVICE_PORT: 8050
        
            OIDC_HOST: keycloak
            OIDC_PORT: 8030
            OIDC_CLIENT_SECRET: toCVmF8WwCQM1YvJtSYfDgAiKSSzeVf8
        ports:
            - 8080:8080
        networks:
            - internal

    flight:
        build:
            dockerfile: Dockerfile.flight
        container_name: flight_service    
        restart: always
        environment:
            SERVICE_HOST: flight_service
            SERVICE_PORT: 8060

            DB_HOST: postgres
        depends_on:
            - postgres
        ports:
            - 8060:8060
        networks:
            - internal

    ticket:
        build:
            dockerfile: Dockerfile.ticket
        container_name: ticket_serivce
        restart: always
        environment:
            SERVICE_HOST: ticket_serivce
            SERVICE_PORT: 8070

            FLIGHT_SERVICE_HOST: gateway
            FLIGHT_SERVICE_PORT: 8080

            BONUS_SERVICE_HOST: gateway
            BONUS_SERVICE_PORT: 8080

            DB_HOST: postgres

            OIDC_HOST: keycloak
            OIDC_PORT: 8030
            OIDC_CLIENT_SECRET: toCVmF8WwCQM1YvJtSYfDgAiKSSzeVf8
        depends_on:
            - postgres
        ports:
            - 8070:8070
        networks:
            - internal

    bonus:
        build:
            dockerfile: Dockerfile.bonus
        container_name: bonus_service
        restart: always
        environment:
            SERVICE_HOST: bonus_service
            SERVICE_PORT: 8050

            DB_HOST: postgres

            OIDC_HOST: keycloak
            OIDC_PORT: 8030
            OIDC_CLIENT_SECRET: toCVmF8WwCQM1YvJtSYfDgAiKSSzeVf8
        depends_on:
            - postgres
        ports:
            - 8050:8050
        networks:
            - internal
    
    keycloak:
        image: quay.io/keycloak/keycloak
        container_name: keycloak
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin

            KC_HOSTNAME: localhost
            KC_HTTP_PORT: 8030
            KC_HTTP_ENABLED: true

            KEYCLOAK_FRONTEND_URL: http://localhost:8030

            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: program
            KC_DB_PASSWORD: program_password
        command: start-dev
        depends_on:
            - postgres
        ports:
            - 8030:8030
        networks:
            - internal

volumes:
    postgresql:

networks:
    internal:
