version: "3"
services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: program
            POSTGRES_PASSWORD: program_password
        volumes:
            - postgresql:/var/lib/postgresql
            - ./postgres/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
        networks:
            - internal

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: program
            RABBITMQ_DEFAULT_PASS: program_password
        ports:
          - 5672:5672
          - 15672:15672 # gui port
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - internal

    gateway:
        image: nginx:latest
        container_name: gateway
        restart: always
        environment:
            NGINX_PORT: 8080
            FLIGHT_HOST: flight_service
            FLIGHT_PORT: 8060
            TICKET_HOST: ticket_serivce
            TICKET_PORT: 8070
            BONUS_HOST: bonus_service
            BONUS_PORT: 8050
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - 8080:8080
        networks:
            - internal

    flight:
        build:
            dockerfile: Dockerfile.flight
        container_name: flight_service    
        restart: always
        environment:
            SERVICE_HOST: flight_service
            SERVICE_PORT: 8060
            DB_HOST: postgres
        networks:
            - internal

    ticket:
        build:
            dockerfile: Dockerfile.ticket
        container_name: ticket_serivce
        restart: always
        environment:
            SERVICE_HOST: ticket_serivce
            SERVICE_PORT: 8070
            FLIGHT_SERVICE_HOST: gateway
            FLIGHT_SERVICE_PORT: 8080
            BONUS_SERVICE_HOST: gateway
            BONUS_SERVICE_PORT: 8080
            DB_HOST: postgres
        networks:
            - internal

    bonus:
        build:
            dockerfile: Dockerfile.bonus
        container_name: bonus_service
        restart: always
        environment:
            SERVICE_HOST: bonus_service
            SERVICE_PORT: 8050
            DB_HOST: postgres
        networks:
            - internal

volumes:
    postgresql:
    rabbitmq:

networks:
    internal:
