version: "3"
services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: program
            POSTGRES_PASSWORD: program_password
        volumes:
            - postgresql:/var/lib/postgresql
        ports:
            - 5432:5432

volumes:
    postgresql: