apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start-dev
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: program_password
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/keycloak
            - name: KC_DB_USERNAME
              value: program
            - name: KC_HOSTNAME
              value: keycloak
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_PORT
              value: "8030"
            - name: KC_LOG_LEVEL
              value: DEBUG
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak
          name: keycloak
          ports:
            - containerPort: 8030
          resources: {}
      restartPolicy: Always
status: {}
