apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ticket
  name: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticket
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: ticket
    spec:
      containers:
        - env:
            - name: BONUS_SERVICE_HOST
              value: gateway.default.svc.cluster.local
            - name: BONUS_SERVICE_PORT
              value: "8080"
            - name: DB_HOST
              value: postgres
            - name: FLIGHT_SERVICE_HOST
              value: gateway.default.svc.cluster.local
            - name: FLIGHT_SERVICE_PORT
              value: "8080"
            - name: SERVICE_HOST
              value: 0.0.0.0
            - name: SERVICE_PORT
              value: "8070"
          image: avekarpov/ticketservice-ticket
          imagePullPolicy: "Always"
          name: ticket-serivce
          ports:
            - containerPort: 8070
          resources: {}
      restartPolicy: Always
status: {}
