apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: bonus
  name: bonus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bonus
  template:
    metadata:
      labels:
        service: bonus
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: postgres
            - name: SERVICE_HOST
              value: 0.0.0.0
            - name: SERVICE_PORT
              value: "8050"
          image: avekarpov/ticketservice-bonus
          imagePullPolicy: Always
          name: bonus-service
          ports:
            - containerPort: 8050
      restartPolicy: Always
