apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    service: gateway
