apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: flight
  name: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      service: flight
  template:
    metadata:
      labels:
        service: flight
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: postgres
            - name: SERVICE_HOST
              value: 0.0.0.0
            - name: SERVICE_PORT
              value: "8060"
          image: avekarpov/ticketservice-flight
          imagePullPolicy: Always
          name: flight
          ports:
            - containerPort: 8060
      restartPolicy: Always
