flight:
  service:
    type: ClusterIP
    port: 8060
    image: avekarpov/ticketservice-flight
    env:
      DB_HOST: postgres
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8060

bonus:
  service:
    type: ClusterIP
    port: 8050
    image: avekarpov/ticketservice-bonus
    env:
      DB_HOST: postgres
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8050

ticket:
  service:
    type: ClusterIP
    port: 8070
    image: avekarpov/ticketservice-ticket
    env:
      DB_HOST: postgres
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8070
      BONUS_SERVICE_HOST: gateway.default.svc.cluster.local
      BONUS_SERVICE_PORT: 8080
      FLIGHT_SERVICE_HOST: gateway.default.svc.cluster.local
      FLIGHT_SERVICE_PORT: 8080

gateway:
   service:
    type: NodePort
    port: 8080
    nodePort: 30000
    image: avekarpov/ticketservice-gateway
    env:
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8080
      BONUS_SERVICE_HOST: bonus.default.svc.cluster.local
      BONUS_SERVICE_PORT: 8050
      FLIGHT_SERVICE_HOST: flight.default.svc.cluster.local
      FLIGHT_SERVICE_PORT: 8060
      TICKET_SERVICE_HOST: ticket.default.svc.cluster.local
      TICKET_SERVICE_PORT: 8070